# Generated by Django 3.2 on 2023-07-31 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate', '0002_rename_user_id_authuserextenstion_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthUserExtenstion',
            new_name='AuthUserExtension',
        ),
    ]
